---
- name: Provision MacOS
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../vars/mac_os_vars.yml

  tasks:
    - import_tasks: tasks/os_settings.yml
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/applications.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/development.yml
